# Borrowed significantly from:
#   - https://circleci.com/docs/2.0/language-haskell/
#   - https://www.stackbuilders.com/news/dr-hakyll-create-a-github-page-with-hakyll-and-circleci

version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-12.26
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b8:42:f3:b5:9e:2a:94:09:c6:75:dd:4f:2d:73:da:97"
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - hakyll-build-stack-cache-v3-
      - run:
          name: Set Stack Root Directory
          command: echo 'export STACK_ROOT="${HOME}/project/.stack-root"' >> $BASH_ENV
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Build project
          command: stack build -j1
      - run:
          name: Build site
          command: stack run rebuild
      - save_cache:
          name: Cache Dependencies
          key: hakyll-build-stack-cache-v3-{{ checksum "johnsonwj-github-io.cabal" }}
          paths:
            - ".stack-work"
            - ".stack-root"
      - deploy:
          # https://stackoverflow.com/questions/5143795/how-can-i-check-in-a-bash-script-if-my-local-git-repository-has-changes
          name: Deploy site to GitHub Pages
          command: |
            git config --global user.email circleci@circleci
            git config --global user.name CircleCI
            git submodule init
            git submodule update
            cd deployed
            git checkout master
            rm -r ./*
            cp -r ../_site/* .
            if git diff-index --quiet HEAD --; then
                echo "no changes; will not deploy"
            else
              git status
              git add --all
              git commit -m "Update (`date -u '+%Y-%m-%dT%H:%M:%SZ'`) [ci skip]"
              git push origin master
              cd ..
              git status
              git add deployed/
              git commit -m "Update deployed (`date -u '+%Y-%m-%dT%H:%M:%SZ'`) [ci skip]"
              git push origin hakyll
            fi


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - hakyll

